scene_name: 'bohemian'
base_img_path: 'data/images/bohemian.png'
debug: false

prompt: 'A bohemian living room, colorful textiles, vibrant, eclectic, 4k image, photorealistic'
aux_prompt: 'A bohemian living room, colorful textiles, vibrant, eclectic, 4k image, photorealistic'
depth_estimator:
  mode: "indoor"